run_mode: "ft"
load_model: True
load_dir: "/storage1/yinjie.tang/Active/jerry.kong/gofa_exp/saved_exp/2024-09-25_11:25:25.656384_809"
grad_acc_step: 32
last_epochs: 0
num_epochs: 0
mode: autoencodergen
batch_size: 1
lr: 0.0001
l2: 0.1
selections: True
llm_max_length: 256

val_interval: 4000

train_task_names:
  - arxiv_link
  - arxiv
  - pubmed_node
  - pubmed_link
sample_size_per_task:
  - 40000
  - 80000
  - 5000
  - 5000
hops:
  - 3
  - 3
  - 3
  - 3

train_max_nodes_per_hops:
  - 5
  - 5
  - 5
  - 5
ways: 10
instructs: True

eval_task_names:
  - cora_node
  - cora_link
  - wikics
  - products
  - expla_graph
  - fb15k237
  - scene_graph
inf_sample_size_per_task: 500
inf_hops:
  - 3
  - 3
  - 3
  - 3
  - -1
  - 3
  - -1

inf_max_nodes_per_hops:
  - 10
  - 10
  - 10
  - 10
  - -1
  - 10
  - -1

inf_ways:
  - 7
  - 3
  - 10
  - 10
  - 2
  - 10
  - -1

inf_instructs:
  - True
  - True
  - True
  - True
  - True
  - True
  - True

inf_selections:
  - True
  - True
  - True
  - True
  - True
  - True
  - True

dec_lora: True