run_mode: "ft"
load_model: True
data_root_path: "/storage1/yinjie.tang/Active/feng.jiarui/TAGDataset"
#load_dir: "/storage1/yinjie.tang/Active/feng.jiarui/GOFA/cache_data/best_ckpt_3.pth"
load_dir: "./saved_exp/2024-10-15_00:27:55.427983_164/mem_ckpt.pth"
grad_acc_step: 32
last_epochs: 0
num_epochs: 0
mode: autoencodergen
batch_size: 1
lr: 0.0001
l2: 0.0
selections: True
llm_max_length: 512
mlp_type: llama
gnn_type: full
num_layers: 5
gating: False
interleave: False
val_interval:

train_task_names:
#  - mag240m
#  - wikikg90m
#  - arxiv_link
#  - arxiv
#  - pubmed_link
  - scene_graph

sample_size_per_task:
#  - 100000
#  - 100000
#  - 50000
#  - 200000
  - 10
hops:
#  - 3
#  - 3
#  - 3
#  - 3
  - -1

train_max_nodes_per_hops:
#  - 5
#  - 5
#  - 5
#  - 5
  - -1
ways: 10
instructs: True

eval_task_names:
#  - cora_node
#  - cora_link
#  - wikics
#  - products
#  - expla_graph
#  - fb15k237
  - scene_graph
inf_sample_size_per_task:
#  - 200
#  - 200
#  - 200
  - 200
#  - 1.0
#  - 1.0
#  - 1.0
#  - 15000
#  - 1.0
#  - 15000
#  - 15000
inf_hops:
#  - 3
#  - 3
#  - -1
#  - 3
#  - 2
#  - 3
#  - 3
  - -1
#  - 3
#  - -1

inf_max_nodes_per_hops:
#  - 10
#  - -1
#  - 10
#  - 10
#  - 10
#  - 3
#  - 10
#  - 10
  - -1
#  - 10
#  - -1

inf_ways:
#  - 7
#  - 2
#  - -1
#  - 10
#  - 2
#  - 5
#  - -1
#  - 2
#  - 10
  - -1

inf_instructs:
#  - True
#  - True
#  - True
#  - True
#  - True
#  - True
  - True

inf_selections:
#  - True
#  - True
#  - True
#  - True
#  - True
#  - True
  - True

dec_lora: True