root_path: "./"
data_root_path: "./TAGDataset"
load_dir: "/storage1/yinjie.tang/Active/jerry.kong/gofa_saved_exp/2025-01-10_18:51:19.452845_251/last_epoch_ckpt.pth"
ckpt_path:
ckpt_save_path: "/storage1/yinjie.tang/Active/jerry.kong/gofa_saved_exp"
last_epochs: 0
num_epochs: 1
grad_acc_step: 64
mlp_type: llama
gnn_type: combine
num_layers: 5
trainable_layers: 5
llm_max_length: 256
l2: 0.0
lr: 0.0003
gating: False
interleave: False
mode: mplmgen
base_llm: "mistral7bmplmsparse"
load_model: True
dec_lora: True
merge_lora: True
save_model:
  save: False
  steps:
  monitor: False
  time: 10
  epochs:
  top_k: -1
  last: True
